### ISSUE TITLE
1.5 GUI, running android fails with  [Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null]

### ISSUE THREAD

**Issue by GreenJeans** [appium/appium-dot-app#539]
Android automation that continues to run as expected using the Appium 1.4.13 GUI fails using the 1.5.2 GUI with:

```
[ADB] Checking whether aapt is present 

[ADB] Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/android-manifest.js:88:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null]
```

**Comment by edgy360** [comment]
Are you using the Inspector? If so, do you have all of the required fields set ('App path' in this specific case)? If not, then this is likely a server-side issue (or missing caps).

**Comment by GreenJeans** [comment]
I am not using the inspector - and when I do, I do indeed have all the required fields set, including 'App path'.  Again, works correctly under Appium 1.4.13

**Comment by lnnp1910** [comment]
I had the same issue.. Worked fine with 1.4.13 but failed in 1.5.2.

**Comment by edgy360** [comment]
Then unfortunately this issue is not related to Appium.app, but more due to Appium itself. Please raise on the main Appium project or in Appium Discuss.
