### ISSUE TITLE
Xcode 8 and iOS 10

### ISSUE THREAD

**Issue by vast** [appium/appium-dot-app#575]
After upgrading to Xcode 8 and iOS 10 Appium.app stopped working:

```ruby
Encountered internal error running command: Error: Xcode version [object Object] is not yet supported
```

## Environment

* OS X El Capitan 10.11.6
* Appium.app 1.5.3

Probably related to https://github.com/appium/appium/issues/6752

**Comment by jlipps** [comment]
This is expected. Xcode 8 is only supported by Appium 1.6 and up.

**Comment by dadityad** [comment]
@jlipps where do i get appium1.6.dmg

**Comment by jlipps** [comment]
@dadityad an appium gui version of 1.6 is not yet available.

**Comment by apankov1** [comment]
@jlipps I apologize for bumping closed ticket, but maybe you could help.

I'm pointing Appium.app to the new Appium package in development settings and passing custom server flags to force it to use `XCUITest`: `--automation-name XCUITest`. 

I run into two issues, maybe you know if there is a workaround?

## Case 1

I enable Developer Settings and set custom server flag `--automation-name XCUITest`. Looks like this:
<img width="640" alt="screen shot 2016-10-14 at 12 34 42 pm" src="https://cloud.githubusercontent.com/assets/1150987/19395237/a21e2d6a-920a-11e6-97d5-c553c50c3df1.png">

In iOS settings, I'm forcing device and platform version. Looks like this
<img width="643" alt="screen shot 2016-10-14 at 12 35 55 pm" src="https://cloud.githubusercontent.com/assets/1150987/19395268/c97d18c6-920a-11e6-8ab5-edf9fefda958.png">

In this case, it seems that custom flag is being ignored. Log

```
Launching Appium with command: /Users/andrewpankov/Documents/src/mobile-automation/node_modules/.bin/appium --port "4724" --pre-launch --log-timestamp --log-level "debug" --platform-version "9.3" --platform-name "iOS" --app "/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app" --full-reset --show-ios-log --show-ios-log --device-name "iPhone 6s" --native-instruments-lib --automation-name XCUITest

2016-10-14 16:36:52:582 - [Appium] Welcome to Appium v1.6.0 (REV 9f241f7a1d7d134267f11dbdc93827e37c245451)

2016-10-14 16:36:52:583 - [Appium] Non-default server args:

2016-10-14 16:36:52:585 - [Appium]   port: 4724
2016-10-14 16:36:52:585 - [Appium]   launch: true
2016-10-14 16:36:52:585 - [Appium]   logTimestamp: true
2016-10-14 16:36:52:586 - [Appium]   platformName: 'iOS'
2016-10-14 16:36:52:586 - [Appium]   platformVersion: '9.3'
2016-10-14 16:36:52:586 - [Appium]   automationName: 'XCUITest'
2016-10-14 16:36:52:586 - [Appium]   deviceName: 'iPhone 6s'
2016-10-14 16:36:52:587 - [Appium]   app: '/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app'
2016-10-14 16:36:52:587 - [Appium]   fullReset: true
2016-10-14 16:36:52:587 - [Appium]   nativeInstrumentsLib: true
2016-10-14 16:36:52:587 - [Appium]   showIOSLog: true
2016-10-14 16:36:52:588 - [Appium] Deprecated server args:
2016-10-14 16:36:52:588 - [Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
2016-10-14 16:36:52:588 - [Appium]   --platform-version => --default-capabilities '{"platformVersion":"9.3"}'
2016-10-14 16:36:52:588 - [Appium]   --automation-name => --default-capabilities '{"automationName":"XCUITest"}'
2016-10-14 16:36:52:588 - [Appium]   --device-name => --default-capabilities '{"deviceName":"iPhone 6s"}'
2016-10-14 16:36:52:588 - [Appium]   --app => --default-capabilities '{"app":"/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app"}'
2016-10-14 16:36:52:589 - [Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
2016-10-14 16:36:52:589 - [Appium]   --native-instruments-lib => --default-capabilities '{"nativeInstrumentsLib":true}'
2016-10-14 16:36:52:589 - [Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
2016-10-14 16:36:52:589 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2016-10-14 16:36:52:599 - [Appium]   platformName: 'iOS'
2016-10-14 16:36:52:600 - [Appium]   platformVersion: '9.3'
2016-10-14 16:36:52:600 - [Appium]   automationName: 'XCUITest'
2016-10-14 16:36:52:600 - [Appium]   deviceName: 'iPhone 6s'
2016-10-14 16:36:52:600 - [Appium]   app: '/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app'
2016-10-14 16:36:52:600 - [Appium]   fullReset: true
2016-10-14 16:36:52:600 - [Appium]   nativeInstrumentsLib: true
2016-10-14 16:36:52:600 - [Appium]   showIOSLog: true

2016-10-14 16:36:52:634 - [Appium] Appium REST http interface listener started on 0.0.0.0:4724

2016-10-14 16:36:53:399 - [HTTP] --> GET /wd/hub/status {}

2016-10-14 16:36:53:400 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []

2016-10-14 16:36:53:412 - [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0"...
2016-10-14 16:36:53:417 - [HTTP] <-- GET /wd/hub/status 200 16 ms - 121 

2016-10-14 16:37:02:155 - [HTTP] --> GET /wd/hub/status {}

2016-10-14 16:37:02:156 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []

2016-10-14 16:37:02:166 - [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0"...

2016-10-14 16:37:02:168 - [HTTP] <-- GET /wd/hub/status 200 12 ms - 121 
2016-10-14 16:37:02:169 - [HTTP] --> GET /wd/hub/sessions {}
2016-10-14 16:37:02:169 - [MJSONWP] Calling AppiumDriver.getSessions() with args: []
2016-10-14 16:37:02:171 - [MJSONWP] Responding to client with driver.getSessions() result: []
2016-10-14 16:37:02:172 - [HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40 
2016-10-14 16:37:02:189 - [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"9.3","newCommandTimeout":"7200","app":"/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app","automationName":"Appium","deviceName":"iPhone 6s"}}
2016-10-14 16:37:02:190 - [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","pla...
2016-10-14 16:37:02:191 - [Appium] Creating new IosDriver session
2016-10-14 16:37:02:191 - [Appium] Capabilities:
2016-10-14 16:37:02:192 - [Appium]   platformName: 'iOS'
2016-10-14 16:37:02:192 - [Appium]   platformVersion: '9.3'
2016-10-14 16:37:02:192 - [Appium]   newCommandTimeout: '7200'
2016-10-14 16:37:02:193 - [Appium]   app: '/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app'
2016-10-14 16:37:02:193 - [Appium]   automationName: 'Appium'
2016-10-14 16:37:02:193 - [Appium]   deviceName: 'iPhone 6s'
2016-10-14 16:37:02:193 - [Appium]   fullReset: true
2016-10-14 16:37:02:194 - [Appium]   nativeInstrumentsLib: true
2016-10-14 16:37:02:194 - [Appium]   showIOSLog: true
2016-10-14 16:37:02:197 - [BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
2016-10-14 16:37:02:201 - [BaseDriver] Session created with session id: b08e1142-4a96-4d9b-86ca-813f7efa12b1

2016-10-14 16:37:02:240 - [debug] [iOS] Xcode version set to 8.0

2016-10-14 16:37:02:269 - [iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (lib/driver.js:120:28)
    at tryCatch (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 { SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (lib/driver.js:120:28)
    at tryCatch (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) jsonwpCode: 33 }

2016-10-14 16:37:02:272 - [HTTP] <-- POST /wd/hub/session 500 83 ms - 243 

2016-10-14 16:37:04:489 - [HTTP] --> GET /wd/hub/status {}

2016-10-14 16:37:04:490 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-10-14 16:37:04:515 - [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0"...
2016-10-14 16:37:04:517 - [HTTP] <-- GET /wd/hub/status 200 27 ms - 121 
```

## Case 2

I don't force device settings in iOS settings 
<img width="643" alt="screen shot 2016-10-14 at 12 39 27 pm" src="https://cloud.githubusercontent.com/assets/1150987/19395368/47cf8060-920b-11e6-98b7-a9d80223495e.png">

and passing everything in developer settings
![screen shot 2016-10-14 at 12 45 13 pm](https://cloud.githubusercontent.com/assets/1150987/19395532/164ca1ac-920c-11e6-8043-7c100307df8a.png)

In this case, it's complaining about missing deviceName capability.  

```
Launching Appium with command: /Users/andrewpankov/Documents/src/mobile-automation/node_modules/.bin/appium --port "4724" --pre-launch --log-timestamp --log-level "debug" --platform-version "9.3" --platform-name "iOS" --app "/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app" --full-reset --show-ios-log --show-ios-log --default-device --native-instruments-lib --automation-name XCUITest --platform-name iPhone6s --platform-version 9.2


2016-10-14 16:46:28:478 - [Appium] Welcome to Appium v1.6.0 (REV 9f241f7a1d7d134267f11dbdc93827e37c245451)

2016-10-14 16:46:28:480 - [Appium] Non-default server args:

2016-10-14 16:46:28:481 - [Appium]   port: 4724
2016-10-14 16:46:28:482 - [Appium]   launch: true
2016-10-14 16:46:28:482 - [Appium]   logTimestamp: true
2016-10-14 16:46:28:482 - [Appium]   defaultDevice: true
2016-10-14 16:46:28:482 - [Appium]   platformName: 'iPhone6s'
2016-10-14 16:46:28:482 - [Appium]   platformVersion: '9.2'

2016-10-14 16:46:28:483 - [Appium]   automationName: 'XCUITest'
2016-10-14 16:46:28:483 - [Appium]   app: '/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app'
2016-10-14 16:46:28:483 - [Appium]   fullReset: true
2016-10-14 16:46:28:484 - [Appium]   nativeInstrumentsLib: true
2016-10-14 16:46:28:484 - [Appium]   showIOSLog: true
2016-10-14 16:46:28:485 - [Appium] Deprecated server args:
2016-10-14 16:46:28:485 - [Appium]   --platform-name => --default-capabilities '{"platformName":"iPhone6s"}'
2016-10-14 16:46:28:485 - [Appium]   --platform-version => --default-capabilities '{"platformVersion":"9.2"}'
2016-10-14 16:46:28:485 - [Appium]   --automation-name => --default-capabilities '{"automationName":"XCUITest"}'
2016-10-14 16:46:28:485 - [Appium]   --app => --default-capabilities '{"app":"/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app"}'
2016-10-14 16:46:28:485 - [Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
2016-10-14 16:46:28:486 - [Appium]   --native-instruments-lib => --default-capabilities '{"nativeInstrumentsLib":true}'
2016-10-14 16:46:28:486 - [Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
2016-10-14 16:46:28:486 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

2016-10-14 16:46:28:496 - [Appium]   platformName: 'iPhone6s'

2016-10-14 16:46:28:496 - [Appium]   platformVersion: '9.2'
2016-10-14 16:46:28:496 - [Appium]   automationName: 'XCUITest'
2016-10-14 16:46:28:496 - [Appium]   app: '/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app'
2016-10-14 16:46:28:497 - [Appium]   fullReset: true
2016-10-14 16:46:28:497 - [Appium]   nativeInstrumentsLib: true
2016-10-14 16:46:28:497 - [Appium]   showIOSLog: true

2016-10-14 16:46:28:524 - [Appium] Appium REST http interface listener started on 0.0.0.0:4724

2016-10-14 16:46:28:808 - [HTTP] --> GET /wd/hub/status {}

2016-10-14 16:46:28:811 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []

2016-10-14 16:46:28:822 - [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0"...

2016-10-14 16:46:28:828 - [HTTP] <-- GET /wd/hub/status 200 16 ms - 121 

2016-10-14 16:46:39:970 - [HTTP] --> GET /wd/hub/status {}

2016-10-14 16:46:39:971 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []

2016-10-14 16:46:39:980 - [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0"...

2016-10-14 16:46:39:982 - [HTTP] <-- GET /wd/hub/status 200 11 ms - 121 

2016-10-14 16:46:46:226 - [HTTP] --> GET /wd/hub/status {}

2016-10-14 16:46:46:226 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []

2016-10-14 16:46:46:252 - [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0"...

2016-10-14 16:46:46:255 - [HTTP] <-- GET /wd/hub/status 200 29 ms - 121 

2016-10-14 16:46:46:256 - [HTTP] --> GET /wd/hub/sessions {}

2016-10-14 16:46:46:256 - [MJSONWP] Calling AppiumDriver.getSessions() with args: []

2016-10-14 16:46:46:257 - [MJSONWP] Responding to client with driver.getSessions() result: []

2016-10-14 16:46:46:258 - [HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40 

2016-10-14 16:46:46:269 - [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"9.3","newCommandTimeout":"7200","app":"/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app","automationName":"Appium"}}
2016-10-14 16:46:46:270 - [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","pla...

2016-10-14 16:46:46:271 - [Appium] Creating new IosDriver session

2016-10-14 16:46:46:271 - [Appium] Capabilities:
2016-10-14 16:46:46:272 - [Appium]   platformName: 'iOS'

2016-10-14 16:46:46:272 - [Appium]   platformVersion: '9.3'
2016-10-14 16:46:46:272 - [Appium]   newCommandTimeout: '7200'
2016-10-14 16:46:46:272 - [Appium]   app: '/Users/andrewpankov/Documents/src/mobile-automation/app/Newsela.app'
2016-10-14 16:46:46:272 - [Appium]   automationName: 'Appium'
2016-10-14 16:46:46:272 - [Appium]   fullReset: true

2016-10-14 16:46:46:272 - [Appium]   nativeInstrumentsLib: true
2016-10-14 16:46:46:272 - [Appium]   showIOSLog: true

2016-10-14 16:46:46:275 - [BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior

2016-10-14 16:46:46:297 - [BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): deviceName can't be blank.
    at IosDriver.validateDesiredCaps (lib/basedriver/driver.js:131:25)
    at IosDriver.validateDesiredCaps (lib/driver.js:43:16)
    at IosDriver.callee$0$0$ (lib/basedriver/commands/session.js:14:8)
    at tryCatch (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.callee$0$0 [as createSession] (lib/basedriver/commands/session.js:8:46)
    at IosDriver.createSession$ (lib/driver.js:43:16)
    at tryCatch (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.createSession (lib/driver.js:118:14)
    at AppiumDriver.createSession$ (lib/appium.js:150:43)
    at tryCatch (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/andrewpankov/Documents/src/mobile-automation/node_m
2016-10-14 16:46:46:301 - [HTTP] <-- POST /wd/hub/session 500 31 ms - 198 

odules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (lib/appium.js:150:31)
    at lib/basedriver/driver.js:174:24
    at tryCatcher (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
 { SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): deviceName can't be blank.
    at IosDriver.validateDesiredCaps (lib/basedriver/driver.js:131:25)
    at IosDriver.validateDesiredCaps (lib/driver.js:43:16)
    at IosDriver.callee$0$0$ (lib/basedriver/commands/session.js:14:8)
    at tryCatch (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Use
rs/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.callee$0$0 [as createSession] (lib/basedriver/commands/session.js:8:46)
    at IosDriver.createSession$ (lib/driver.js:43:16)
    at tryCatch (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.createSession (lib/driver.js:118:14)
    at AppiumDriver.createSession$ (lib/appium.js:150:43)
    at tryCatch (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (lib/appium.js:150:31)
    at lib/basedriver/driver.js:174:24
    at tryCatcher (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node
_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/andrewpankov/Documents/src/mobile-automation/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5) jsonwpCode: 33 }
```

What do you think?

**Comment by jlipps** [comment]
@apankov1 in case 1 the issue is that your test is sending `automationName: Appium` which is overriding your server flag.

**Comment by apankov1** [comment]
@jlipps I'm not running the test, I'm trying to launch inspector. 

I fixed my tests to use `XCUITest` and they work fine, it's an inspector I need. Sorry that I didn't mention it my comment above.

**Comment by jlipps** [comment]
Well then it's a problem in appium-dot-app that it's sending `automationName: Appium` when it's trying to start the inspector. It's overriding the correct automationName. I guess you'll need to figure out where that's happening and change it, or wait for a dot-app code update.

**Comment by apankov1** [comment]
@jlipps, thanks, that's what I've been trying to figure out before I posted the question above.

**Comment by vikramvi** [comment]
@jlipps can you please re-open this ticket as it's not working with steps mentioned by @apankov1

**Comment by reach2jeyan** [comment]
I cant use the appium 1.6 for element identification at this moment with Xcode 8 installed? Any work arounds for this? with Appium 1.5.3?
