### ISSUE TITLE
Xcode 8 and iOS 10 and Inspector

### ISSUE THREAD

**Issue by baliand** [appium/appium-dot-app#577]
I can't use nappium-dot-app for iOS 10 with xCode 8

I know about appium@1.6.0-beta2 and It's working but I can't understand one thing. 
How Can I use Inspector? 

Thanks for help

**Comment by serhatbolsu** [comment]
I would love to see this answered, is there a workaround I can use right now ?

**Comment by chauchinyiu** [comment]
me too , got the same issue. please fix it.

**Comment by IntelloScooby** [comment]
Following this thread. I have the same issue. How can I inspect elements after upgrading to Xcode 8

**Comment by chenchaoyi** [comment]
Try [these](https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958#.rix6y7vde) options, either one should be able to help.

**Comment by mgmanikandan87** [comment]
Hi all,

Currently, appium 1.6 is not available in GUI to inspect the elements, but there is workaround you can get the elements. 

Try this :

https://www.youtube.com/watch?v=4BgkVp0v3BM

This video might help you guys

**Comment by tateexon** [comment]
Technically you can launch appium 1.6 from a terminal in a directory that has an appium.txt that looks something like this:
[caps]
platformName = "iOS"
app = "<path and app>"
deviceName = "iPhone 7"
platformVersion = 10.1

Then launch the appium gui, under general settings you can select the "Use Remote Server" check box and then hit the Inspector button. The app will launch and the gui will be able to read the apps elements.

**Comment by vikramvi** [comment]
as per https://github.com/appium/appium-dot-app/issues/575 , I tried option but it's not working 
![screen shot 2016-11-21 at 2 47 38 pm](https://cloud.githubusercontent.com/assets/308490/20484897/ada1e408-aff9-11e6-9d40-f9b3da116d1f.png)


```
[debug] [iOS] Xcode version set to 8.0

[iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (lib/driver.js:130:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 { SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (lib/driver.js:130:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) jsonwpCode: 33 }
```

**Comment by vikramvi** [comment]
@tateexon I tried your solution but getting error as below

Is there some additional settings need to be done ?

```
[debug] [iOS] Xcode version set to 8.0
[iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (lib/driver.js:130:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 { SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (lib/driver.js:130:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7) jsonwpCode: 33 }
[HTTP] <-- POST /wd/hub/session 500 12 ms - 243 

```

**Comment by vikramvi** [comment]
@chenchaoyi I tried option mentioned in the link but getting below error



`[debug] [iOS] Xcode version set to 8.0
[iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (lib/driver.js:130:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 { SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (lib/driver.js:130:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) jsonwpCode: 33 }
[HTTP] <-- POST /wd/hub/session 500 78 ms - 243`

**Comment by tateexon** [comment]
Here are all my settings I have set in the gui just in case they are important and I didn't know it:
![screen shot 2016-11-21 at 8 33 40 am](https://cloud.githubusercontent.com/assets/10238396/20488825/b2ee4c28-afc5-11e6-863d-4220dbba6a46.png)
![screen shot 2016-11-21 at 8 35 40 am](https://cloud.githubusercontent.com/assets/10238396/20488846/bee10228-afc5-11e6-9f4e-498e7832d6af.png)
![screen shot 2016-11-21 at 8 36 23 am](https://cloud.githubusercontent.com/assets/10238396/20488858/cac0775e-afc5-11e6-9acc-d6bfe40e88ac.png)

**Comment by vikramvi** [comment]
@tateexon You're my hero of the day. Thanks a ton for detailed info.

I had wrong setting in appium.txt and also was not sure how to select 10.1 for Platform Version under Device Settings. One had to just write the version number here.

On side note if somebody wants to run on older iOS version, they need to input 
automationName = "XCUITest"  inside appium.txt

**Comment by vikramvi** [comment]
@jlipps can you please look into this issue, since long time this project is not being updated or maintained. 

Thanks in advance.

**Comment by jlipps** [comment]
This project is no longer maintained. We're building an entirely new inspector app at https://github.com/appium/appium-desktop. we won't be doing any more work to update or fix this version.

**Comment by puneetbohra** [comment]
@vikramvi I am also getting the same error, i have set the Appium UI but still getting the same error. 
Also i have set all fields on the Appium UI (1.4.13) which is shared by @tateexon 
Following are my logs : - 

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"10.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 7"},null,null,null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.1'
[Appium]   newCommandTimeout: '999999'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'iPhone 7'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Capability 'newCommandTimeout' changed from string ('999999') to integer (999999). This may cause unexpected behavior
[XCUITest] Error: The desired capabilities must include either an app or a bundleId for iOS
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.validateDesiredCaps (../../lib/driver.js:576:11)
    at XCUITestDriver.callee$0$0$ (../../../../lib/basedriver/commands/session.js:14:8)
    at tryCatch (/Users/kirankumar/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kirankumar/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kirankumar/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/kirankumar/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/kirankumar/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/Users/kirankumar/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/kirankumar/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/kirankumar/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/kirankumar/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as createSession] (../../../../lib/basedriver/commands/session.js:8:46)
    at XCUITestDriver.createSession$ (../../lib/driver.js:73:21)
