### ISSUE TITLE
Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node

### ISSUE THREAD

**Issue by sjenasears** [appium/appium-dot-app#583]
Getting following error
Error: Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (../../lib/certificate.js:5:32)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (../../lib/utils.js:7:36)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (../../lib/simulator-xcode-6.js:7:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-simulator/build/lib/simulator.js:11:24)
    at Module._compile (module.js:413:34)

Xcode v - 8.2.1
Appium version - 1.6.3

**Comment by imurchie** [comment]
Please move to `appium-desktop`
